version: "3.8"

services:
  mysqldb:
    image: mariadb:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - $MYSQLDB_LOCAL_PORT:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-u",
          "${MYSQLDB_USER}",
          "--password=${MYSQLDB_ROOT_PASSWORD}",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

volumes:
  db:
